// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yabhcilwgtcwozfaikez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhYmhjaWx3Z3Rjd296ZmFpa2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDAwNTQsImV4cCI6MjA3Mjg3NjA1NH0.PIvSlp5fVD72jPMPfOHH-A9LSIEOjEj4i2yOt6WPKkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});